#  Intro to Data Science 

## Week 1 

## Numpy and Pandas 

# Numpy 

    - Multidimensions arrays and matrix.
    - Mathematics functions.
# Pandas 
    - Handle data as way suited to analysis
    - similar to R 
## Both common on Data analysis
# ___ ___ ___ __ ___ __ __ ___ __ ___ __ ___ __

# Numpy 
    - Functions usufull for statistical analysis
        * Mean.
        * Median.
        * Standard deviation.
       

In [1]:
## Importing numpy 
import numpy as np

In [3]:
numbers = [1,2,3,4,5]
np.mean(numbers)

3.0

In [4]:
np.median(numbers)

3.0

In [5]:
np.std(numbers)

1.4142135623730951

The array object class is the foundation of Numpy, and Numpy arrays are like
lists in Python, except that every thing inside an array must be of the
same type, like int or float.

In [18]:
array = np.array([1, 4, 5, 8], int)
print (array)
print ("")
array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
print (array)

[1 4 5 8]

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
# Matrix indexing and slicing
array = np.array([1, 4, 5, 8], float)
print (array)
print ("")
print (array[1])
print ("")
print (array[:3])
print ("")
array[1] = 5.0
print (array[1])

[1. 4. 5. 8.]

4.0

[1. 4. 5.]

5.0


In [20]:
# arithmetic operations with numpy arrays 
if True:
    two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
    print (two_D_array)
    print ("")
    print (two_D_array[1][1])
    print ("")
    print (two_D_array[1, :])
    print ("")
    print (two_D_array[:, 2])

[[1. 2. 3.]
 [4. 5. 6.]]

5.0

[4. 5. 6.]

[3. 6.]


In [22]:
# Matrix araithmetics 
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print (array_1 + array_2)
    print ("")
    print (array_1 - array_2)
    print ("")
    print (array_1 * array_2)

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]


In [25]:
# extra functions for later use 
# dot product / mean ect..
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print (np.mean(array_1))
    print (np.mean(array_2))
    print ("")
    print (np.dot(array_1, array_2))

2.0
7.0

[44.]


## Note 1 
### What is dot product
https://www.mathsisfun.com/algebra/vectors-dot-product.html

There are two vector A and B and we have to find the dot product and cross product of two vector array. Dot product is also known as scalar product and cross product also known as vector product.

### Dot Product  : 
Let we have given two vector A = a1 * i + a2 * j + a3 * k and B = b1 * i + b2 * j + b3 * k. Where i, j and k are the unit vector along the x, y and z directions. Then dot product is calculated as dot product = a1 * b1 + a2 * b2 + a3 * b3

### Example - 
A = 3 * i + 5 * j + 4 * k
B = 2 * i + 7 * j + 5 * k

dot product = 3 * 2 + 5 * 7 + 4 * 5

            = 6 + 35 + 20
            = 61

## Cross product : https://www.mathsisfun.com/algebra/vectors-cross-product.html

https://betterexplained.com/articles/cross-product/

In [32]:
array1  = np.array([1,2,3])
array2  = np.array([4,5,6])
print(np.dot(array1,array2))
cross = np.cross(array1,array2)
print(cross)
print(np.linalg.norm(cross))

32
[-3  6 -3]
7.3484692283495345


## Pandas 
- Dataframes : 2D labled data structure with colums which can be diff data types 
- Nan = no data 
    

In [40]:
# import pandas 
import pandas as pd 

You can think of Series as an one-dimensional object that is similar to
an array, list, or column in a database. By default, it will assign an
index label to each item in the Series ranging from 0 to N, where N is
the number of items in the Series minus one.

In [44]:
if True:
    series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
    print (series)

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object


In [55]:
# use index to select specific items from the Series 
if True:
    series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
    print (series['Instructor'])
    print ("")
    print (series[['Instructor', 'Curriculum Manager', 'Course Number']])

Dave

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object


In [58]:
# You can also use boolean operators to select specific items from the Series
if True:
    cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
    print (cuteness > 3)
    print ("")
    print (cuteness[cuteness > 3])


Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool

Puppy     4
Kitten    5
dtype: int64


to create a dataframe, you can pass a dictionary of lists to the Dataframe
constructor:

1) The key of the dictionary will be the column name.
2) The associating list will be the values within that column.

In [131]:
if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print(football)

   year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12


# Pandas 
also has various functions that will help you understand some basic
information about your data frame. Some of these functions are:
- dtypes: to get the datatype for each column
- describe: useful for seeing basic statistics of the dataframe's numerical
   columns
- head: displays the first five rows of the dataset
- tail: displays the last five rows of the dataset


In [63]:
if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print (football.dtypes)
    print ("")
    print (football.describe())
    print ("")
    print (football.head())
    print ("")
    print (football.tail())

year       int64
team      object
wins       int64
losses     int64
dtype: object

              year       wins     losses
count     8.000000   8.000000   8.000000
mean   2011.125000   9.375000   6.625000
std       0.834523   3.377975   3.377975
min    2010.000000   4.000000   1.000000
25%    2010.750000   7.500000   5.000000
50%    2011.000000  10.000000   6.000000
75%    2012.000000  11.000000   8.500000
max    2012.000000  15.000000  12.000000

   year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5

   year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12


## Quiz 1 
Create a pandas dataframe called 'olympic_medal_counts_df' containing
    the data from the table of 2014 Sochi winter olympics medal counts.  

    The columns for this dataframe should be called 
    'country_name', 'gold', 'silver', and 'bronze'.  
    There is no need to  specify row indexes for this dataframe 
    (in this case, the rows will automatically be assigned numbered indexes).
    



In [127]:
# answer quiz 1 : 

data = {'Countries' : ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan'],
        'gold' :  [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       'silver' : [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0],
       'bronze ' : [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]}
df = pd.DataFrame(data)
(df)

Countries  gold  silver  bronze 
0     Russian Fed.    13      11        9
1           Norway    11       5       10
2           Canada    10      10        5
3    United States     9       7       12
4      Netherlands     8       7        9
5          Germany     8       6        5
6      Switzerland     6       3        2
7          Belarus     5       0        1
8          Austria     4       8        5
9           France     4       4        7
10          Poland     4       1        1
11           China     3       4        2
12           Korea     3       3        2
13          Sweden     2       7        6
14  Czech Republic     2       4        2
15        Slovenia     2       2        4
16           Japan     1       4        3
17         Finland     1       3        1
18   Great Britain     1       1        2
19         Ukraine     1       0        1
20        Slovakia     1       0        0
21           Italy     0       2        6
22          Latvia     0       2        2
23       Australia     0       2        1
24         Croatia     0       1        0
25      Kazakhstan     0       0        1

## Indexing DataFrames 
1) Selecting a single column from the DataFrame will return a Series.

2) Selecting multiple columns from the DataFrame will return a DataFrame.



In [70]:
if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print (football['year'])
    print ('')
    print (football.year)  # shorthand for football['year']
    print ('')
    print (football[['year', 'wins', 'losses']])

0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64

0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64

   year  wins  losses
0  2010    11       5
1  2011     8       8
2  2012    10       6
3  2011    15       1
4  2012    11       5
5  2010     6      10
6  2011    10       6
7  2012     4      12


### Row Selection can be done through multiple ways 

Some of the basic and common methods are:
1) Slicing.
   
2) An individual index (through the functions iloc or loc).
   
3) Boolean indexing

You can also combine multiple selection requirements through boolean
operators like & (and) or | (or)

In [82]:
if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print (football.iloc[[0]])
    print ("")
    print (football.loc[[0]])
    print ("")
    print (football[3:5])
    print ("")
    print (football[football.wins > 10])
    print ("")
    print (football[(football.wins > 10) & (football.team == "Packers")])


   year   team  wins  losses
0  2010  Bears    11       5

   year   team  wins  losses
0  2010  Bears    11       5

   year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5

   year     team  wins  losses
0  2010    Bears    11       5
3  2011  Packers    15       1
4  2012  Packers    11       5

   year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5


map() can only be used on a Series to return a new Series and applymap() can only be used on a DataFrame to return a new DataFrame.

# َQuiz 2 
____________
Using the dataframe's apply method, create a new Series called 
avg_medal_count that indicates the average number of gold, silver,
and bronze medals earned amongst countries who earned at 
least one medal of any kind at the 2014 Sochi olympics.  Note that
the countries list already only includes countries that have earned
at least one medal. No additional filtering is necessary.
    
You do not need to call the function in your code when running it in the
browser - the grader will do that automatically when you submit or test it.
    

In [119]:
import numpy
from pandas import DataFrame, Series

countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']
gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]
    
olympic_medal_counts = {'country_name':countries,
                            'gold': Series(gold),
                            'silver': Series(silver),
                            'bronze': Series(bronze)}    
df = DataFrame(olympic_medal_counts)

In [123]:
print(df)

country_name  gold  silver  bronze
0     Russian Fed.    13      11       9
1           Norway    11       5      10
2           Canada    10      10       5
3    United States     9       7      12
4      Netherlands     8       7       9
5          Germany     8       6       5
6      Switzerland     6       3       2
7          Belarus     5       0       1
8          Austria     4       8       5
9           France     4       4       7
10          Poland     4       1       1
11           China     3       4       2
12           Korea     3       3       2
13          Sweden     2       7       6
14  Czech Republic     2       4       2
15        Slovenia     2       2       4
16           Japan     1       4       3
17         Finland     1       3       1
18   Great Britain     1       1       2
19         Ukraine     1       0       1
20        Slovakia     1       0       0
21           Italy     0       2       6
22          Latvia     0       2       2
23       Australia     0       2       1
24         Croatia     0       1       0
25      Kazakhstan     0       0       1

In [102]:
avg_metal_count = df[['gold','silver', 'bronze']].apply(np.mean)
print(avg_metal_count)

gold      3.807692
silver    3.730769
bronze    3.807692
dtype: float64


# Quiz 3

 Imagine a point system in which each country is awarded 4 points for each
    gold medal,  2 points for each silver medal, and one point for each 
    bronze medal.  

    Using the numpy.dot function, create a new dataframe called 
    'olympic_points_df' that includes:
        a) a column called 'country_name' with the country name
        b) a column called 'points' with the total number of points the country
           earned at the Sochi olympics.
           
    You do not need to call the function in your code when running it in the
    browser - the grader will do that automatically when you submit or test it.
    '''

In [115]:
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']

gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]

In [126]:
points = (np.array(df[['gold','silver','bronze']]).dot([4,2,1]))
obympic_point = {'country_name' : countries , 'points' : points }
obympic_point_df = DataFrame(obympic_point)
(obympic_point_df)

country_name  points
0     Russian Fed.      83
1           Norway      64
2           Canada      65
3    United States      62
4      Netherlands      55
5          Germany      49
6      Switzerland      32
7          Belarus      21
8          Austria      37
9           France      31
10          Poland      19
11           China      22
12           Korea      20
13          Sweden      28
14  Czech Republic      18
15        Slovenia      16
16           Japan      15
17         Finland      11
18   Great Britain       8
19         Ukraine       5
20        Slovakia       4
21           Italy      10
22          Latvia       6
23       Australia       5
24         Croatia       2
25      Kazakhstan       1

# End of Lesson 1

Mohamedadelmohamed997@gmail.com